#############################################################################
# Makefile for building: bin/QMTSim
# Generated by qmake (2.01a) (Qt 4.4.3) on: Thu Jan 15 16:58:59 2009
# Project:  QMTSim.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile QMTSim.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iip -Iosc -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtScript -lQtSql -lQtXmlPatterns -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = ip/IpEndpointName.cpp \
		osc/OscOutboundPacketStream.cpp \
		osc/OscTypes.cpp \
		src/TUIOSender.cpp \
		src/TUIOanimation.cpp \
		src/aboutQMTSimImpl.cpp \
		src/addcusordialogimpl.cpp \
		src/addellipsedialogimpl.cpp \
		src/configuredialogimpl.cpp \
		src/dialogimpl.cpp \
		src/item.cpp \
		src/main.cpp \
		src/mainwindowimpl.cpp \
		src/readcursor.cpp \
		src/readellipse.cpp \
		src/readpolygon.cpp \
		src/scenecursor.cpp \
		src/sceneellipse.cpp \
		src/setpathscene.cpp \
		src/setpathwinodwimpl.cpp \
		src/table.cpp \
		src/tangible_type.cpp \
		src/debugWindowImpl.cpp \
		src/readmeDialogImpl.cpp \
		src/resizeTableDialogImpl.cpp \
		ip/posix/NetworkingUtils.cpp \
		ip/posix/UdpSocket.cpp build/moc_TUIOSender.cpp \
		build/moc_aboutQMTSimImpl.cpp \
		build/moc_addcusordialogimpl.cpp \
		build/moc_addellipsedialogimpl.cpp \
		build/moc_configuredialogimpl.cpp \
		build/moc_dialogimpl.cpp \
		build/moc_mainwindowimpl.cpp \
		build/moc_setpathscene.cpp \
		build/moc_setpathwinodwimpl.cpp \
		build/moc_debugWindowImpl.cpp \
		build/moc_readmeDialogImpl.cpp \
		build/moc_resizeTableDialogImpl.cpp \
		qrc_resource.cpp
OBJECTS       = build/IpEndpointName.o \
		build/OscOutboundPacketStream.o \
		build/OscTypes.o \
		build/TUIOSender.o \
		build/TUIOanimation.o \
		build/aboutQMTSimImpl.o \
		build/addcusordialogimpl.o \
		build/addellipsedialogimpl.o \
		build/configuredialogimpl.o \
		build/dialogimpl.o \
		build/item.o \
		build/main.o \
		build/mainwindowimpl.o \
		build/readcursor.o \
		build/readellipse.o \
		build/readpolygon.o \
		build/scenecursor.o \
		build/sceneellipse.o \
		build/setpathscene.o \
		build/setpathwinodwimpl.o \
		build/table.o \
		build/tangible_type.o \
		build/debugWindowImpl.o \
		build/readmeDialogImpl.o \
		build/resizeTableDialogImpl.o \
		build/NetworkingUtils.o \
		build/UdpSocket.o \
		build/moc_TUIOSender.o \
		build/moc_aboutQMTSimImpl.o \
		build/moc_addcusordialogimpl.o \
		build/moc_addellipsedialogimpl.o \
		build/moc_configuredialogimpl.o \
		build/moc_dialogimpl.o \
		build/moc_mainwindowimpl.o \
		build/moc_setpathscene.o \
		build/moc_setpathwinodwimpl.o \
		build/moc_debugWindowImpl.o \
		build/moc_readmeDialogImpl.o \
		build/moc_resizeTableDialogImpl.o \
		build/qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		QMTSim.pro
QMAKE_TARGET  = QMTSim
DESTDIR       = bin/
TARGET        = bin/QMTSim

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_additem.h build/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QMTSim.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtScript.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXmlPatterns.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile QMTSim.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtScript.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXmlPatterns.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile QMTSim.pro

dist: 
	@$(CHK_DIR_EXISTS) build/QMTSim1.0.0 || $(MKDIR) build/QMTSim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/QMTSim1.0.0/ && $(COPY_FILE) --parents ip/IpEndpointName.h ip/NetworkingUtils.h ip/PacketListener.h ip/TimerListener.h ip/UdpSocket.h osc/MessageMappingOscPacketListener.h osc/OscException.h osc/OscHostEndianness.h osc/OscOutboundPacketStream.h osc/OscTypes.h src/TUIOSender.h src/TUIOanimation.h src/TouchData.h src/aboutQMTSim.h src/aboutQMTSimImpl.h src/addcursordialog.h src/addcusordialogimpl.h src/addellipsedialog.h src/addellipsedialogimpl.h src/configuredialog.h src/configuredialogimpl.h src/dialogimpl.h src/item.h src/mainwindowimpl.h src/scenecursor.h src/sceneellipse.h src/setpathscene.h src/setpathwindow.h src/setpathwinodwimpl.h src/table.h src/tangible_type.h src/debugWindow.h src/debugWindowImpl.h src/readmeDialog.h src/readmeDialogImpl.h src/resizeTableDialog.h src/resizeTableDialogImpl.h build/QMTSim1.0.0/ && $(COPY_FILE) --parents resource.qrc build/QMTSim1.0.0/ && $(COPY_FILE) --parents ip/IpEndpointName.cpp osc/OscOutboundPacketStream.cpp osc/OscTypes.cpp src/TUIOSender.cpp src/TUIOanimation.cpp src/aboutQMTSimImpl.cpp src/addcusordialogimpl.cpp src/addellipsedialogimpl.cpp src/configuredialogimpl.cpp src/dialogimpl.cpp src/item.cpp src/main.cpp src/mainwindowimpl.cpp src/readcursor.cpp src/readellipse.cpp src/readpolygon.cpp src/scenecursor.cpp src/sceneellipse.cpp src/setpathscene.cpp src/setpathwinodwimpl.cpp src/table.cpp src/tangible_type.cpp src/debugWindowImpl.cpp src/readmeDialogImpl.cpp src/resizeTableDialogImpl.cpp ip/posix/NetworkingUtils.cpp ip/posix/UdpSocket.cpp build/QMTSim1.0.0/ && $(COPY_FILE) --parents ui/additem.ui ui/mainwindow.ui build/QMTSim1.0.0/ && (cd `dirname build/QMTSim1.0.0` && $(TAR) QMTSim1.0.0.tar QMTSim1.0.0 && $(COMPRESS) QMTSim1.0.0.tar) && $(MOVE) `dirname build/QMTSim1.0.0`/QMTSim1.0.0.tar.gz . && $(DEL_FILE) -r build/QMTSim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_TUIOSender.cpp build/moc_aboutQMTSimImpl.cpp build/moc_addcusordialogimpl.cpp build/moc_addellipsedialogimpl.cpp build/moc_configuredialogimpl.cpp build/moc_dialogimpl.cpp build/moc_mainwindowimpl.cpp build/moc_setpathscene.cpp build/moc_setpathwinodwimpl.cpp build/moc_debugWindowImpl.cpp build/moc_readmeDialogImpl.cpp build/moc_resizeTableDialogImpl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_TUIOSender.cpp build/moc_aboutQMTSimImpl.cpp build/moc_addcusordialogimpl.cpp build/moc_addellipsedialogimpl.cpp build/moc_configuredialogimpl.cpp build/moc_dialogimpl.cpp build/moc_mainwindowimpl.cpp build/moc_setpathscene.cpp build/moc_setpathwinodwimpl.cpp build/moc_debugWindowImpl.cpp build/moc_readmeDialogImpl.cpp build/moc_resizeTableDialogImpl.cpp
build/moc_TUIOSender.cpp: src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/TUIOSender.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/TUIOSender.h -o build/moc_TUIOSender.cpp

build/moc_aboutQMTSimImpl.cpp: src/aboutQMTSim.h \
		src/aboutQMTSimImpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/aboutQMTSimImpl.h -o build/moc_aboutQMTSimImpl.cpp

build/moc_addcusordialogimpl.cpp: src/addcursordialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/addcusordialogimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/addcusordialogimpl.h -o build/moc_addcusordialogimpl.cpp

build/moc_addellipsedialogimpl.cpp: src/sceneellipse.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/addellipsedialogimpl.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/addellipsedialogimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/addellipsedialogimpl.h -o build/moc_addellipsedialogimpl.cpp

build/moc_configuredialogimpl.cpp: src/configuredialog.h \
		src/TUIOSender.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/configuredialogimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/configuredialogimpl.h -o build/moc_configuredialogimpl.cpp

build/moc_dialogimpl.cpp: build/ui_additem.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/dialogimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogimpl.h -o build/moc_dialogimpl.cpp

build/moc_mainwindowimpl.cpp: src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/mainwindowimpl.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_setpathscene.cpp: src/setpathscene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/setpathscene.h -o build/moc_setpathscene.cpp

build/moc_setpathwinodwimpl.cpp: src/setpathwindow.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/setpathscene.h \
		src/setpathwinodwimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/setpathwinodwimpl.h -o build/moc_setpathwinodwimpl.cpp

build/moc_debugWindowImpl.cpp: src/debugWindow.h \
		src/debugWindowImpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/debugWindowImpl.h -o build/moc_debugWindowImpl.cpp

build/moc_readmeDialogImpl.cpp: src/readmeDialog.h \
		src/readmeDialogImpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/readmeDialogImpl.h -o build/moc_readmeDialogImpl.cpp

build/moc_resizeTableDialogImpl.cpp: src/resizeTableDialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		build/ui_mainwindow.h \
		src/resizeTableDialogImpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/resizeTableDialogImpl.h -o build/moc_resizeTableDialogImpl.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		logo.png \
		icons/ellipse.png \
		icons/polygon.png \
		icons/exit.png \
		icons/qt4.png \
		icons/upload.png \
		icons/debug.png \
		icons/save.png \
		icons/cursor.png \
		icons/view.png \
		icons/resize.png \
		icons/readme.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_additem.h build/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_additem.h build/ui_mainwindow.h
build/ui_additem.h: ui/additem.ui
	/usr/bin/uic-qt4 ui/additem.ui -o build/ui_additem.h

build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o build/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/IpEndpointName.o: ip/IpEndpointName.cpp ip/IpEndpointName.h \
		ip/NetworkingUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/IpEndpointName.o ip/IpEndpointName.cpp

build/OscOutboundPacketStream.o: osc/OscOutboundPacketStream.cpp osc/OscOutboundPacketStream.h \
		osc/OscTypes.h \
		osc/OscException.h \
		osc/OscHostEndianness.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/OscOutboundPacketStream.o osc/OscOutboundPacketStream.cpp

build/OscTypes.o: osc/OscTypes.cpp osc/OscTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/OscTypes.o osc/OscTypes.cpp

build/TUIOSender.o: src/TUIOSender.cpp src/TUIOSender.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TUIOSender.o src/TUIOSender.cpp

build/TUIOanimation.o: src/TUIOanimation.cpp src/TUIOanimation.h \
		src/tangible_type.h \
		src/TouchData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TUIOanimation.o src/TUIOanimation.cpp

build/aboutQMTSimImpl.o: src/aboutQMTSimImpl.cpp src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/aboutQMTSimImpl.o src/aboutQMTSimImpl.cpp

build/addcusordialogimpl.o: src/addcusordialogimpl.cpp src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/scenecursor.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/addcusordialogimpl.o src/addcusordialogimpl.cpp

build/addellipsedialogimpl.o: src/addellipsedialogimpl.cpp src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/addellipsedialogimpl.o src/addellipsedialogimpl.cpp

build/configuredialogimpl.o: src/configuredialogimpl.cpp src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/configuredialogimpl.o src/configuredialogimpl.cpp

build/dialogimpl.o: src/dialogimpl.cpp src/dialogimpl.h \
		build/ui_additem.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dialogimpl.o src/dialogimpl.cpp

build/item.o: src/item.cpp src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/item.o src/item.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h \
		src/dialogimpl.h \
		build/ui_additem.h \
		src/setpathwinodwimpl.h \
		src/setpathwindow.h \
		src/setpathscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/readcursor.o: src/readcursor.cpp src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/readcursor.o src/readcursor.cpp

build/readellipse.o: src/readellipse.cpp src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/readellipse.o src/readellipse.cpp

build/readpolygon.o: src/readpolygon.cpp src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/readpolygon.o src/readpolygon.cpp

build/scenecursor.o: src/scenecursor.cpp src/scenecursor.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scenecursor.o src/scenecursor.cpp

build/sceneellipse.o: src/sceneellipse.cpp src/sceneellipse.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sceneellipse.o src/sceneellipse.cpp

build/setpathscene.o: src/setpathscene.cpp src/setpathscene.h \
		src/setpathwinodwimpl.h \
		src/setpathwindow.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/setpathscene.o src/setpathscene.cpp

build/setpathwinodwimpl.o: src/setpathwinodwimpl.cpp src/setpathwinodwimpl.h \
		src/setpathwindow.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/setpathscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/setpathwinodwimpl.o src/setpathwinodwimpl.cpp

build/table.o: src/table.cpp src/table.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/table.o src/table.cpp

build/tangible_type.o: src/tangible_type.cpp src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/tangible_type.o src/tangible_type.cpp

build/debugWindowImpl.o: src/debugWindowImpl.cpp src/debugWindowImpl.h \
		src/debugWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debugWindowImpl.o src/debugWindowImpl.cpp

build/readmeDialogImpl.o: src/readmeDialogImpl.cpp src/readmeDialogImpl.h \
		src/readmeDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/readmeDialogImpl.o src/readmeDialogImpl.cpp

build/resizeTableDialogImpl.o: src/resizeTableDialogImpl.cpp src/resizeTableDialogImpl.h \
		src/resizeTableDialog.h \
		src/mainwindowimpl.h \
		src/item.h \
		src/tangible_type.h \
		src/TouchData.h \
		src/TUIOanimation.h \
		src/addellipsedialogimpl.h \
		src/sceneellipse.h \
		src/addellipsedialog.h \
		src/addcusordialogimpl.h \
		src/addcursordialog.h \
		src/scenecursor.h \
		src/configuredialogimpl.h \
		src/configuredialog.h \
		src/TUIOSender.h \
		src/table.h \
		src/aboutQMTSimImpl.h \
		src/aboutQMTSim.h \
		src/debugWindowImpl.h \
		src/debugWindow.h \
		src/readmeDialogImpl.h \
		src/readmeDialog.h \
		build/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/resizeTableDialogImpl.o src/resizeTableDialogImpl.cpp

build/NetworkingUtils.o: ip/posix/NetworkingUtils.cpp ip/NetworkingUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/NetworkingUtils.o ip/posix/NetworkingUtils.cpp

build/UdpSocket.o: ip/posix/UdpSocket.cpp ip/UdpSocket.h \
		ip/NetworkingUtils.h \
		ip/IpEndpointName.h \
		ip/PacketListener.h \
		ip/TimerListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/UdpSocket.o ip/posix/UdpSocket.cpp

build/moc_TUIOSender.o: build/moc_TUIOSender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_TUIOSender.o build/moc_TUIOSender.cpp

build/moc_aboutQMTSimImpl.o: build/moc_aboutQMTSimImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_aboutQMTSimImpl.o build/moc_aboutQMTSimImpl.cpp

build/moc_addcusordialogimpl.o: build/moc_addcusordialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_addcusordialogimpl.o build/moc_addcusordialogimpl.cpp

build/moc_addellipsedialogimpl.o: build/moc_addellipsedialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_addellipsedialogimpl.o build/moc_addellipsedialogimpl.cpp

build/moc_configuredialogimpl.o: build/moc_configuredialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_configuredialogimpl.o build/moc_configuredialogimpl.cpp

build/moc_dialogimpl.o: build/moc_dialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dialogimpl.o build/moc_dialogimpl.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_setpathscene.o: build/moc_setpathscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_setpathscene.o build/moc_setpathscene.cpp

build/moc_setpathwinodwimpl.o: build/moc_setpathwinodwimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_setpathwinodwimpl.o build/moc_setpathwinodwimpl.cpp

build/moc_debugWindowImpl.o: build/moc_debugWindowImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_debugWindowImpl.o build/moc_debugWindowImpl.cpp

build/moc_readmeDialogImpl.o: build/moc_readmeDialogImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_readmeDialogImpl.o build/moc_readmeDialogImpl.cpp

build/moc_resizeTableDialogImpl.o: build/moc_resizeTableDialogImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_resizeTableDialogImpl.o build/moc_resizeTableDialogImpl.cpp

build/qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

